EOF = ""
NULL = "\u0000"

NEWLINE = "\u000A"
FORM_FEED = "\u000C"
CARRIAGE_RETURN = "\u000D"
TAB = "\u0009"
SPACE = "\u0020"

REPLACEMENT_CHARACTER = "\uFFFD"

WHITESPACE = (TAB, NEWLINE, FORM_FEED, CARRIAGE_RETURN, SPACE)

ASCII_DIGIT = "0123456789"
ASCII_UPPER_HEX_DIGIT = ASCII_DIGIT + "ABCDEF"
ASCII_LOWER_HEX_DIGIT = ASCII_DIGIT + "abcdef"
ASCII_HEX_DIGIT = ASCII_UPPER_HEX_DIGIT + ASCII_LOWER_HEX_DIGIT
ASCII_UPPER_ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
ASCII_LOWER_ALPHA = "abcdefghijklmnopqrstuvwxyz"
ASCII_ALPHA = ASCII_LOWER_ALPHA + ASCII_UPPER_ALPHA
ASCII_ALPHANUMERIC = ASCII_ALPHA + ASCII_DIGIT
